version: '3.5'

services:
  laravel-app:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: reminder
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    networks:
      backend:
        aliases:
          - laravel-app
    depends_on:
      - mysql-db

  mysql-db:
    image: mariadb:latest
    container_name: mysql-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=reminder
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    networks:
      backend:
        aliases:
          - db

networks:
  backend:
    name: backend-network